<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Recipe;

use App\Recipe\Data\Recipe;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\EventStreamResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\ServerEvent;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveAction;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\DefaultActionTrait;

#[AsLiveComponent('recipe')]
final class TwigComponent extends AbstractController
{
    use DefaultActionTrait;

    #[LiveProp(writable: true)]
    public ?string $message = null;

    #[LiveProp(writable: true)]
    public ?string $shareEmail = null;

    #[LiveProp]
    public bool $shareOpen = false;

    public function __construct(
        private readonly Chat $chat,
        private readonly MailerInterface $mailer,
    ) {
    }

    public function getRecipe(): ?Recipe
    {
        try {
            return $this->chat->getRecipe();
        } catch (\RuntimeException) {
            return null;
        }
    }

    public function isAwaitingRecipe(): bool
    {
        return $this->chat->isAwaitingRecipe();
    }

    #[LiveAction]
    public function submit(): void
    {
        if (null === $this->message || '' === trim($this->message)) {
            return;
        }

        $this->chat->submitMessage($this->message);

        $this->message = null;
    }

    public function streamContent(Request $request): EventStreamResponse
    {
        // The chat is kept in a session-scoped cache, so make sure the session id is
        // available; the streamed body itself never touches the session, which lets the
        // framework close (and unlock) it before the response is sent.
        $request->getSession()->start();

        $messages = $this->chat->loadMessages();

        return new EventStreamResponse(function () use ($messages) {
            foreach ($this->chat->getRecipeStream($messages) as $recipe) {
                yield new ServerEvent(explode("\n", $this->renderBlockView('components/_recipe_stream.html.twig', 'update', ['recipe' => $recipe])));
            }

            yield new ServerEvent(explode("\n", $this->renderBlockView('components/_recipe_stream.html.twig', 'end')));
        });
    }

    #[LiveAction]
    public function reset(): void
    {
        $this->chat->reset();
    }

    #[LiveAction]
    public function openShare(): void
    {
        $this->shareOpen = true;
    }

    #[LiveAction]
    public function closeShare(): void
    {
        $this->shareOpen = false;
    }

    #[LiveAction]
    public function share(): void
    {
        if (null === $this->shareEmail || '' === trim($this->shareEmail)) {
            return;
        }

        if (false === filter_var($this->shareEmail, \FILTER_VALIDATE_EMAIL)) {
            return;
        }

        $recipe = $this->getRecipe();
        if (null === $recipe) {
            return;
        }

        $body = $recipe->toString().\PHP_EOL.\PHP_EOL.'Generated by https://github.com/symfony/ai-demo';

        $email = (new Email())
            ->from('noreply@symfony-ai.demo')
            ->to($this->shareEmail)
            ->subject(\sprintf('Recipe: %s', $recipe->name))
            ->text($body);

        $this->mailer->send($email);

        $this->shareOpen = false;
        $this->shareEmail = null;
    }
}
