name: Docs Build

on:
    pull_request:
        paths:
            - '**.rst'
            - 'docs/**'
            - '.github/workflows/docs-build.yaml'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    docs-build:
        name: docs-builder
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.5

            - name: Install dependencies
              uses: ramsey/composer-install@v4
              with:
                  working-directory: docs/_build

            - name: Build the docs
              working-directory: docs/_build
              run: vendor/bin/docs-builder build:docs .. output --disable-cache --fail-on-errors --save-errors=errors.log

            - name: Show build errors
              if: failure()
              working-directory: docs/_build
              run: cat errors.log
