name: Run Examples

on:
    workflow_dispatch:

defaults:
    run:
        working-directory: examples

jobs:
    run-examples:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install root dependencies
              uses: ramsey/composer-install@v4
              with:
                  working-directory: "."

            - name: Build packages
              working-directory: .
              run: php .github/build-packages.php

            - name: Install dependencies
              uses: ramsey/composer-install@v4
              with:
                  working-directory: "examples"

            - name: Run OpenAI examples
              id: run-examples
              run: ./runner openai
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
